### ISSUE TITLE
Enhancement - GUI Scaling

### ISSUE THREAD

**Issue by ivarkallejarv** [dlebansais/PgSurveyor-Disclosed#10]
Currently the program doesn't have any setting to change GUI scaling.
It would be nice if the UI elements of the program could be altered by a setting of sorts to apply easier to different scaling values.
It doesn't block you from doing the surveys or managing them, but it takes a bit of fiddling to make it work

Reproduction:
- Change GUI Scaling in PG from 1 to 1.75 or 2
- Run PGSurveyor and set up surveys

Result:
All the elements are slightly off from where they should be

PS: Thank you for the app, it works very well and makes it a lot easier to do surveying.

**Comment by dlebansais** [comment]
I'm using a GUI scaling of 2.0 and it works fine for me. I've tried 1.0, still good. Can you post screenshots so I can see what you mean by slightly off?

+ Setup PGSurveyor normally for your surveying session.
+ Select a starting point different than where you are.
+ Take a Windows screenshot (not game screenshot) so I can see what you have on your monitor.
