### ISSUE TITLE
Border boxes inaccessible

### ISSUE THREAD

**Issue by NavarreDR** [dlebansais/PgSurveyor-Disclosed#3]
When I launch pgsurveyor (per step 5: "Two shiny, colored borders are displayed. The red border is for the map window, the purple border for the inventory window.") I only see the top-left drag-handle for the Red border box.  The bottom-right handle and purple border are not visible...  Presumably, this is expecting a lower resolution or similar?  Current resolution is 3840x2160.  I am in windowed mode.  Thank you!

**Comment by dlebansais** [comment]
Resolution should not be the problem (I'm using lower). In case like this the solution is to drag the top-left corner that you can see all the way down and right till it's barely visible, and the entire application is outside the screen.
If you're on a two-monitors system (or more) don't hesitate to drag corners on a screen with smaller resolution where borders don't even show up.
Then press Alt+F4 to close the app. Restart it, and it will detect the problem and reset to default positions in the middle of the one of the screens.
I just tested it again and while it took me 3 tries before I could manage it, it worked.

**Comment by NavarreDR** [comment]
Thank you for the quick reply! I tried repeatedly to drag the one visible checkbox off the bottom right and then alt+f4, to no avail. 
However, I did locate the registry settings at:  Computer\HKEY_CURRENT_USER\SOFTWARE\Project Gorgon Tools\PgSurveyor.
I modified the x/y coordinate values for MapStart and InventoryStart to low values (ie: MapStart = 200;200;300;250) and that worked!   A 'reset map & inventory bounding boxes' hot key combo would be a nice addition if you get the chance. Thanks!

**Comment by dlebansais** [comment]
Glad to know you found a solution to your problem.
I agree a reset method would be nice, but when the problem arises usually there is no button to click or menu to see. I could put something in place that is simple to reach (key, right-click menu or whatever) but then I'm concerned about accidental reset and interference in general with the rest of the app.
I was hoping the current method would work better. I might revisit it and improve it instead.
