### ISSUE TITLE
Border boxes start in inaccessible position on 3840x2160

### ISSUE THREAD

**Issue by granbluebeepboop** [dlebansais/PgSurveyor-Disclosed#5]
![image](https://user-images.githubusercontent.com/38770561/181652329-598407e4-f034-4eaf-b63d-829d80ddde50.png)

The only way I could find to fix this was to change my resolution to 1080p so that it would spawn in the correct position, and then change back to 4k.

**Comment by dlebansais** [comment]
I recently added the 'reset' command-line parameter. This will reset positions when the program is started (use only once, obviously). This is described in the troubleshooting section also added recently at the end of the readme.

**Comment by granbluebeepboop** [comment]
![image](https://user-images.githubusercontent.com/38770561/181840623-27e5b041-99e6-489c-9e40-807602922530.png)

That is the starting position. Resetting does not fix it.

**Comment by jacoblusk** [comment]
Seems the only way to fix is either change resolution to 1920x1080, or modify the settings in the registry as suggested by issue https://github.com/dlebansais/PgSurveyor-Disclosed/issues/3

**Comment by dlebansais** [comment]
It looks like I need to put my hand on a 4K monitor to fix that. Thank you for the report anyway.
