### ISSUE TITLE
Purple border issue

### ISSUE THREAD

**Issue by Raize** [dlebansais/PgSurveyor-Disclosed#6]
There appears to be an issue on 4k monitors with the purple border. It goes all the way to right and then off the screen by default, so when I reset, it doesn't matter because the original border is off the screen. I'll attach an image.
<img width="1245" alt="PGSurveyor_bug" src="https://user-images.githubusercontent.com/2079416/188347497-a76ec1e6-734e-4df4-94b2-e6ad1de312d8.png">

**Comment by dlebansais** [comment]
It's a bit cumbersome, but you can fix this issue by changing some values in the registry. This [other issue](https://github.com/dlebansais/PgSurveyor-Disclosed/issues/3) contains the relevant info.

Unfortunately, I don't have a 4K monitor that I could use to find a fix for this.
